config/routes.rb
RolifyTutorial::Application.routes.draw do
  devise_for :users, :path_names => { :sign_up => "Register"}

    resources :jims
    resources :mikes
    resources :leos
    resources :fact_pages

  root :to => 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Create guest user aka. anonymous (not logged-in) when user is nil.
    user ||= User.new

    if user.has_role? :admin
      can :manage, :all
    else
      # logged in user
      if user.has_role? :user
        can :manage, Jim, :user_id => user.id
        can :read, Mike, :user_id => user.id
        can :read, Leo, :user_id => user.id
      
        cannot :manage, Mike, :user_id => user.id 
        cannot :manage, Leo, :user_id => user.id 
      end
    end
  end
end

app/models/jim.rb
class Jim < ActiveRecord::Base
  attr_accessible :complaining, :issue

  resourcify
  
end

app/models/leo.rb
class Leo < ActiveRecord::Base
  attr_accessible :complaining, :issue

  resourcify
  
end

app/models/mike.rb
class Mike < ActiveRecord::Base
  attr_accessible :complaining, :issue

  resourcify
  
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username

  after_create :assign_user_role

private

  def assign_user_role
    self.add_role "user"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(user)
    stored_location_for(:user) || fact_pages_path
  end

end

app/controllers/fact_pages_controller.rb
class FactPagesController < ApplicationController
  before_filter :authenticate_user!
  
  def index; end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/jims_controller.rb
class JimsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_complaint, except: [:index, :new, :create]

  def index
    @jims = Jim.all
  end

  def new
    @jim = Jim.new
  end

  def create
    @jim = Jim.new(params[:jim])
    if @jim.save
      redirect_to @jim, notice: "Jim you can now read whats wrong."
    else
      flash[:alert] = "Complaint has not been created."
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @jim.update_attributes(params[:jim])
      flash[:alert] = "Complaint has been updated."
      redirect_to jim_path
    else
      flash[:alert] = "Complaint has not been created."
      render :action => "edit"
    end
  end

  def destroy
    @jim.destroy
    flash[:alert] = "Complaint has been deleted."
    redirect_to jims_path
  end

  def find_complaint
    @jim = Jim.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The Complaint you were looking for could not be found."
      redirect_to jims_path
  end
end

app/controllers/leos_controller.rb
class LeosController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_complaint, except: [:index, :new, :create]

  def index
    @leos = Leo.all
  end

  def new
    @leo = Leo.new
  end

  def create
    @leo = Leo.new(params[:leo])
    if @leo.save
      redirect_to @leo, notice: "Leo you can now read whats wrong."
    else
      flash[:alert] = "Complaint has not been created."
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @leo.update_attributes(params[:leo])
      flash[:alert] = "Complaint has been updated."
      redirect_to leo_path
    else
      flash[:alert] = "Complaint has not been created."
      render :action => "edit"
    end
  end

  def destroy
    @leo.destroy
    flash[:alert] = "Complaint has been deleted."
    redirect_to leos_path
  end

  def find_complaint
    @leo = Leo.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The Complaint you were looking for could not be found."
      redirect_to leos_path
  end
end

app/controllers/mikes_controller.rb
class MikesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_complaint, except: [:index, :new, :create]

  def index
    @mikes = Mike.all
  end

  def new
    @mike = Mike.new
  end

  def create
    @mike = Mike.new(params[:mike])
    if @mike.save
      redirect_to @mike, notice: "Mike you can now read whats wrong."
    else
      flash[:alert] = "Complaint has not been created."
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @mike.update_attributes(params[:mike])
      flash[:alert] = "Complaint has been updated."
      redirect_to mike_path
    else
      flash[:alert] = "Complaint has not been created."
      render :action => "edit"
    end
  end

  def destroy
    @mike.destroy
    flash[:alert] = "Complaint has been deleted."
    redirect_to mikes_path
  end

  def find_complaint
    @mike = Mike.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The Complaint you were looking for could not be found."
      redirect_to mikes_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fact_pages_helper.rb
module FactPagesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jims_helper.rb
module JimsHelper
end

app/helpers/leos_helper.rb
module LeosHelper
end

app/helpers/mikes_helper.rb
module MikesHelper
end

app/views/fact_pages/index.html.haml
%h2 How it Works

%strong
  Devise
%ul 
  %li config/locales/devise.en.yml
  %li rails g devise:views
  %li app/controllers/application_controller.rb

%strong
  Cancan
%ul
  %li app/models/ability.rb
  %li app/views/layouts/application.html.haml

%strong 
  Rolify
%ul
  %li app/models/user.rb
  %li rails c

app/views/home/index.html.haml
.small-10.columns
  %h1 Devise, Cancan, Rolify

  %p Hello and welcome to Gage Alan Shaeffers presentation on devise, cancan, and rolify. The gems that are about to be discussed are used for users to be assigned roles and authentacate where they can go and what they can do. 
  %strong Take a look at the table below than click picture to begin the lunch and learn.
  %br
  %br
.small-10.columns
  %table
    %thead
      %tr
        %th Gem
        %th Description
        %th Github page

    %tbody
      %tr
        %td Devise
        %td Devise is a flexible authentication solution for Rails based on Warden.
        %td 
          %a{:href => "https://github.com/plataformatec/devise"} plataformatec/devise
      %tr
        %td Cancan
        %td CanCan is an authorization library for Ruby on Rails which restricts what resources a given user is allowed to access. All permissions are defined in a single location (the Ability class) and not duplicated across controllers, views, and database queries.
        %td 
          %a{:href => 'https://github.com/ryanb/cancan'} ryanb/cancan
      %tr
        %td Rolify
        %td Authorization gem that doesn't provide a role class.
        %td 
          %a{:href => 'https://github.com/EppO/rolify'} EppO/rolify
%div{style:"border: 4px solid #2ba6cb; padding: 5px;"}
  = link_to image_tag('funny-home-button.png'), new_user_registration_path

app/views/jims/_complaint_list.html.haml
%h2 Jims Rant

%table
  %thead
    %tr
      %th Issue
      %th Description
      %th Options
  %tbody
    %tr 
      %td= @jim.issue
      %td= @jim.complaining
      %td
        = link_to "Delete", @jim, method: :delete, data: { confirm: "Are you sure you want to remove this request?"}, class: 'tiny alert button'
        = link_to "Edit", edit_jim_path(@jim), class: 'tiny button'

app/views/jims/edit.html.haml
%h2 Whats wrong Jim

%br
%br

= simple_form_for @jim do |f|
  = f.input :issue, label: "Issue"
  %br
  = f.input :complaining, label: "Description"
  %br
  = f.button :submit

app/views/jims/index.html.haml
.small-12.columns
  %h3
    Jims Rants

.small-12.columns
  - @jims.each do |rant|
    %div{style:"margin: 10px 0; border: 2px solid #f26e25; padding: 5px;"}
      %div
        %strong
          = link_to rant.issue, jim_path(rant)
        %br
          = rant.created_at

.small-12.columns
  %div
    = link_to 'Click here to rant', new_jim_path, class: 'button'

app/views/jims/new.html.haml
%h3 Whats wrong Jim

= simple_form_for @jim do |f|
  = f.input :issue, label: "Issue"
  %br
  = f.input :complaining, label: "Description"
  %br
  = f.button :submit

app/views/jims/show.html.haml
= render 'complaint_list'

= link_to 'Show All Rants', jims_path

/ = render 'complaint_list.html.haml' if @jim

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Lunch & Learn
    /[if IE]
      %script{:type => "text/javascript", :src => "http://html5shim.googlecode.com/svn/trunk/html5.js"}
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
  %body{ data: { controller: "#{controller_name}", action: "#{action_name}" } }
    .fixed
      %nav.top-bar
        %ul.title-area
          %li.name
            = link_to image_tag('gs_logo.png'), root_path
          %li.toggle-topbar
            %a{ href: "#"}
        - if current_user
          %section.top-bar-section
            %ul.left
              - if can? :manage, Jim
                %li
                  = link_to 'Jims Blog', jims_path
                %li
                  = link_to 'Mikes Blog', mikes_path
                %li
                  = link_to 'Leos Blog', leos_path
            %ul.right
              %li
                = link_to 'How it Works', fact_pages_path
              %li.has-dropdown
                = link_to current_user.username, '#', id: 'logged_user'
                %ul.dropdown
                  %li.sign-out= link_to 'Sign Out', destroy_user_session_path, method: :delete
    .container
      .row
        .twelve.columns
          #flash
            - flash.each do |name, msg|
              %div{class: "alert-box #{name == :notice ? "success" : "alert"}"}
                %a{class: "close", href: "#"} &times
                = msg
      .row
        = yield

app/views/leos/_complaint_list.html.haml
%h2 Leos Rant


%table
  %thead
    %tr
      %th Issue
      %th Description
      - if can? :manage, Leo
        %th Options
  %tbody
    %tr 
      %td= @leo.issue
      %td= @leo.complaining
      - if can? :manage, Leo
        %td
          = link_to "Delete", @leo, method: :delete, data: { confirm: "Are you sure you want to remove this request?"}, class: 'tiny alert button'
          = link_to "Edit", edit_leo_path(@leo), class: 'tiny button'

app/views/leos/edit.html.haml
%h2 Whats wrong Leo

%br
%br

= simple_form_for @leo do |f|
  = f.input :issue, label: "Issue"
  %br
  = f.input :complaining, label: "Description"
  %br
  = f.button :submit

app/views/leos/index.html.haml
.small-12.columns
  %h3
    Leos Rants

.small-12.columns
  - if can? :read, Leo
    - @leos.each do |rant|
      %div{style:"margin: 10px 0; border: 2px solid #f26e25; padding: 5px;"}
        %strong
          = link_to rant.issue, leo_path(rant)
        %br
          = rant.created_at
.small-12.columns
  - if can? :manage, Leo
    %div
      = link_to 'Click here to rant', new_leo_path, class: 'button'

app/views/leos/new.html.haml
%h2 Whats wrong Leo

%br
%br

= simple_form_for @leo do |f|
  = f.input :issue, label: "Issue"
  %br
  = f.input :complaining, label: "Description"
  %br
  = f.button :submit

app/views/leos/show.html.haml
= render 'complaint_list'

= link_to 'Show All Rants', leos_path

app/views/mikes/_complaint_list.html.haml
%h2 Mikes Rant

%table
  %thead
    %tr
      %th Issue
      %th Description
      - if can? :manage, Mike
        %th Options
  %tbody
    %tr 
      %td= @mike.issue
      %td= @mike.complaining
      - if can? :manage, Mike
        %td
          = link_to "Delete", @mike, method: :delete, data: { confirm: "Are you sure you want to remove this request?"}, class: 'tiny alert button'
          = link_to "Edit", edit_mike_path(@mike), class: 'tiny button'

app/views/mikes/edit.html.haml
%h2 Whats wrong Mike

%br
%br
- if can? :manage
  = simple_form_for @mike do |f|
    = f.input :issue, label: "Issue"
    %br
    = f.input :complaining, label: "Description"
    %br
    = f.button :submit

app/views/mikes/index.html.haml
.small-12.columns
  %h3
    Mikes Rants

.small-12.columns
  - if can? :read, Mike
    - @mikes.each do |rant|
      %div{style:"margin: 10px 0; border: 2px solid #f26e25; padding: 5px;"}
        %div
          %strong
            = link_to rant.issue, mike_path(rant)
          %br
            = rant.created_at

.small-12.columns
  %div
    - if can? :manage, Mike
      = link_to 'Click here to rant', new_mike_path, class: 'button'

app/views/mikes/new.html.haml
%h2 Whats wrong Mike

%br
%br

= simple_form_for @mike do |f|
  = f.input :issue, label: "Issue"
  %br
  = f.input :complaining, label: "Description"
  %br
  = f.button :submit

app/views/mikes/show.html.haml
= render 'complaint_list'

= link_to 'Show All Rants', mikes_path